insert into DEP (DEPARTMENT_ID, CREATED_DATE, LAST_UPDATED_DATE, DEPARTMENT_NAME, version)
           values(100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'IT', 0);
insert into EMP(EMPLOYEE_ID, CREATED_DATE, LAST_UPDATED_DATE, DEPARTMENT_ID, EMPLOYEE_NAME, version)
          values( 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,100, 'Sabegh', 0);
insert into EMP(EMPLOYEE_ID, CREATED_DATE, LAST_UPDATED_DATE, DEPARTMENT_ID, EMPLOYEE_NAME, version)
          values( 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,100, 'Amitabh', 0);
